/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicVerifyEmailRouteImport } from './routes/_public/verify-email'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as PublicOnboardingIndexRouteImport } from './routes/_public/onboarding/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as PublicOnboardingStep5RouteImport } from './routes/_public/onboarding/step-5'
import { Route as PublicOnboardingStep4RouteImport } from './routes/_public/onboarding/step-4'
import { Route as PublicOnboardingStep3RouteImport } from './routes/_public/onboarding/step-3'
import { Route as PublicOnboardingStep2RouteImport } from './routes/_public/onboarding/step-2'
import { Route as PublicOnboardingStep1RouteImport } from './routes/_public/onboarding/step-1'
import { Route as PublicOnboardingReviewRouteImport } from './routes/_public/onboarding/review'
import { Route as PublicOnboardingCompleteRouteImport } from './routes/_public/onboarding/complete'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminOrganizationsIndexRouteImport } from './routes/_authenticated/admin/organizations/index'
import { Route as AuthenticatedAdminClinicsIndexRouteImport } from './routes/_authenticated/admin/clinics/index'
import { Route as AuthenticatedAdminAdminsIndexRouteImport } from './routes/_authenticated/admin/admins/index'
import { Route as AuthenticatedAdminUsersNewRouteImport } from './routes/_authenticated/admin/users/new'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin/users/$id'
import { Route as AuthenticatedAdminOrganizationsNewRouteImport } from './routes/_authenticated/admin/organizations/new'
import { Route as AuthenticatedAdminOrganizationsIdRouteImport } from './routes/_authenticated/admin/organizations/$id'
import { Route as AuthenticatedAdminClinicsNewRouteImport } from './routes/_authenticated/admin/clinics/new'
import { Route as AuthenticatedAdminClinicsIdRouteImport } from './routes/_authenticated/admin/clinics/$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicVerifyEmailRoute = PublicVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOnboardingIndexRoute = PublicOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicOnboardingStep5Route = PublicOnboardingStep5RouteImport.update({
  id: '/onboarding/step-5',
  path: '/onboarding/step-5',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOnboardingStep4Route = PublicOnboardingStep4RouteImport.update({
  id: '/onboarding/step-4',
  path: '/onboarding/step-4',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOnboardingStep3Route = PublicOnboardingStep3RouteImport.update({
  id: '/onboarding/step-3',
  path: '/onboarding/step-3',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOnboardingStep2Route = PublicOnboardingStep2RouteImport.update({
  id: '/onboarding/step-2',
  path: '/onboarding/step-2',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOnboardingStep1Route = PublicOnboardingStep1RouteImport.update({
  id: '/onboarding/step-1',
  path: '/onboarding/step-1',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOnboardingReviewRoute = PublicOnboardingReviewRouteImport.update({
  id: '/onboarding/review',
  path: '/onboarding/review',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOnboardingCompleteRoute =
  PublicOnboardingCompleteRouteImport.update({
    id: '/onboarding/complete',
    path: '/onboarding/complete',
    getParentRoute: () => PublicRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminOrganizationsIndexRoute =
  AuthenticatedAdminOrganizationsIndexRouteImport.update({
    id: '/admin/organizations/',
    path: '/admin/organizations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminClinicsIndexRoute =
  AuthenticatedAdminClinicsIndexRouteImport.update({
    id: '/admin/clinics/',
    path: '/admin/clinics/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAdminsIndexRoute =
  AuthenticatedAdminAdminsIndexRouteImport.update({
    id: '/admin/admins/',
    path: '/admin/admins/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersNewRoute =
  AuthenticatedAdminUsersNewRouteImport.update({
    id: '/admin/users/new',
    path: '/admin/users/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/admin/users/$id',
    path: '/admin/users/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminOrganizationsNewRoute =
  AuthenticatedAdminOrganizationsNewRouteImport.update({
    id: '/admin/organizations/new',
    path: '/admin/organizations/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminOrganizationsIdRoute =
  AuthenticatedAdminOrganizationsIdRouteImport.update({
    id: '/admin/organizations/$id',
    path: '/admin/organizations/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminClinicsNewRoute =
  AuthenticatedAdminClinicsNewRouteImport.update({
    id: '/admin/clinics/new',
    path: '/admin/clinics/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminClinicsIdRoute =
  AuthenticatedAdminClinicsIdRouteImport.update({
    id: '/admin/clinics/$id',
    path: '/admin/clinics/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/onboarding/complete': typeof PublicOnboardingCompleteRoute
  '/onboarding/review': typeof PublicOnboardingReviewRoute
  '/onboarding/step-1': typeof PublicOnboardingStep1Route
  '/onboarding/step-2': typeof PublicOnboardingStep2Route
  '/onboarding/step-3': typeof PublicOnboardingStep3Route
  '/onboarding/step-4': typeof PublicOnboardingStep4Route
  '/onboarding/step-5': typeof PublicOnboardingStep5Route
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/onboarding/': typeof PublicOnboardingIndexRoute
  '/admin/clinics/$id': typeof AuthenticatedAdminClinicsIdRoute
  '/admin/clinics/new': typeof AuthenticatedAdminClinicsNewRoute
  '/admin/organizations/$id': typeof AuthenticatedAdminOrganizationsIdRoute
  '/admin/organizations/new': typeof AuthenticatedAdminOrganizationsNewRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/admin/users/new': typeof AuthenticatedAdminUsersNewRoute
  '/admin/admins/': typeof AuthenticatedAdminAdminsIndexRoute
  '/admin/clinics/': typeof AuthenticatedAdminClinicsIndexRoute
  '/admin/organizations/': typeof AuthenticatedAdminOrganizationsIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/onboarding/complete': typeof PublicOnboardingCompleteRoute
  '/onboarding/review': typeof PublicOnboardingReviewRoute
  '/onboarding/step-1': typeof PublicOnboardingStep1Route
  '/onboarding/step-2': typeof PublicOnboardingStep2Route
  '/onboarding/step-3': typeof PublicOnboardingStep3Route
  '/onboarding/step-4': typeof PublicOnboardingStep4Route
  '/onboarding/step-5': typeof PublicOnboardingStep5Route
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/onboarding': typeof PublicOnboardingIndexRoute
  '/admin/clinics/$id': typeof AuthenticatedAdminClinicsIdRoute
  '/admin/clinics/new': typeof AuthenticatedAdminClinicsNewRoute
  '/admin/organizations/$id': typeof AuthenticatedAdminOrganizationsIdRoute
  '/admin/organizations/new': typeof AuthenticatedAdminOrganizationsNewRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/admin/users/new': typeof AuthenticatedAdminUsersNewRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsIndexRoute
  '/admin/clinics': typeof AuthenticatedAdminClinicsIndexRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_public/verify-email': typeof PublicVerifyEmailRoute
  '/_public/onboarding/complete': typeof PublicOnboardingCompleteRoute
  '/_public/onboarding/review': typeof PublicOnboardingReviewRoute
  '/_public/onboarding/step-1': typeof PublicOnboardingStep1Route
  '/_public/onboarding/step-2': typeof PublicOnboardingStep2Route
  '/_public/onboarding/step-3': typeof PublicOnboardingStep3Route
  '/_public/onboarding/step-4': typeof PublicOnboardingStep4Route
  '/_public/onboarding/step-5': typeof PublicOnboardingStep5Route
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_public/onboarding/': typeof PublicOnboardingIndexRoute
  '/_authenticated/admin/clinics/$id': typeof AuthenticatedAdminClinicsIdRoute
  '/_authenticated/admin/clinics/new': typeof AuthenticatedAdminClinicsNewRoute
  '/_authenticated/admin/organizations/$id': typeof AuthenticatedAdminOrganizationsIdRoute
  '/_authenticated/admin/organizations/new': typeof AuthenticatedAdminOrganizationsNewRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/_authenticated/admin/users/new': typeof AuthenticatedAdminUsersNewRoute
  '/_authenticated/admin/admins/': typeof AuthenticatedAdminAdminsIndexRoute
  '/_authenticated/admin/clinics/': typeof AuthenticatedAdminClinicsIndexRoute
  '/_authenticated/admin/organizations/': typeof AuthenticatedAdminOrganizationsIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/onboarding/complete'
    | '/onboarding/review'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/onboarding/step-4'
    | '/onboarding/step-5'
    | '/admin/'
    | '/onboarding/'
    | '/admin/clinics/$id'
    | '/admin/clinics/new'
    | '/admin/organizations/$id'
    | '/admin/organizations/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/admin/admins/'
    | '/admin/clinics/'
    | '/admin/organizations/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/onboarding/complete'
    | '/onboarding/review'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/onboarding/step-4'
    | '/onboarding/step-5'
    | '/admin'
    | '/onboarding'
    | '/admin/clinics/$id'
    | '/admin/clinics/new'
    | '/admin/organizations/$id'
    | '/admin/organizations/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/admin/admins'
    | '/admin/clinics'
    | '/admin/organizations'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/reset-password'
    | '/_public/verify-email'
    | '/_public/onboarding/complete'
    | '/_public/onboarding/review'
    | '/_public/onboarding/step-1'
    | '/_public/onboarding/step-2'
    | '/_public/onboarding/step-3'
    | '/_public/onboarding/step-4'
    | '/_public/onboarding/step-5'
    | '/_authenticated/admin/'
    | '/_public/onboarding/'
    | '/_authenticated/admin/clinics/$id'
    | '/_authenticated/admin/clinics/new'
    | '/_authenticated/admin/organizations/$id'
    | '/_authenticated/admin/organizations/new'
    | '/_authenticated/admin/users/$id'
    | '/_authenticated/admin/users/new'
    | '/_authenticated/admin/admins/'
    | '/_authenticated/admin/clinics/'
    | '/_authenticated/admin/organizations/'
    | '/_authenticated/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/verify-email': {
      id: '/_public/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof PublicVerifyEmailRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/onboarding/': {
      id: '/_public/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof PublicOnboardingIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/onboarding/step-5': {
      id: '/_public/onboarding/step-5'
      path: '/onboarding/step-5'
      fullPath: '/onboarding/step-5'
      preLoaderRoute: typeof PublicOnboardingStep5RouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/onboarding/step-4': {
      id: '/_public/onboarding/step-4'
      path: '/onboarding/step-4'
      fullPath: '/onboarding/step-4'
      preLoaderRoute: typeof PublicOnboardingStep4RouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/onboarding/step-3': {
      id: '/_public/onboarding/step-3'
      path: '/onboarding/step-3'
      fullPath: '/onboarding/step-3'
      preLoaderRoute: typeof PublicOnboardingStep3RouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/onboarding/step-2': {
      id: '/_public/onboarding/step-2'
      path: '/onboarding/step-2'
      fullPath: '/onboarding/step-2'
      preLoaderRoute: typeof PublicOnboardingStep2RouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/onboarding/step-1': {
      id: '/_public/onboarding/step-1'
      path: '/onboarding/step-1'
      fullPath: '/onboarding/step-1'
      preLoaderRoute: typeof PublicOnboardingStep1RouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/onboarding/review': {
      id: '/_public/onboarding/review'
      path: '/onboarding/review'
      fullPath: '/onboarding/review'
      preLoaderRoute: typeof PublicOnboardingReviewRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/onboarding/complete': {
      id: '/_public/onboarding/complete'
      path: '/onboarding/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof PublicOnboardingCompleteRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/organizations/': {
      id: '/_authenticated/admin/organizations/'
      path: '/admin/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/clinics/': {
      id: '/_authenticated/admin/clinics/'
      path: '/admin/clinics'
      fullPath: '/admin/clinics/'
      preLoaderRoute: typeof AuthenticatedAdminClinicsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/admins/': {
      id: '/_authenticated/admin/admins/'
      path: '/admin/admins'
      fullPath: '/admin/admins/'
      preLoaderRoute: typeof AuthenticatedAdminAdminsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/new': {
      id: '/_authenticated/admin/users/new'
      path: '/admin/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AuthenticatedAdminUsersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/organizations/new': {
      id: '/_authenticated/admin/organizations/new'
      path: '/admin/organizations/new'
      fullPath: '/admin/organizations/new'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/organizations/$id': {
      id: '/_authenticated/admin/organizations/$id'
      path: '/admin/organizations/$id'
      fullPath: '/admin/organizations/$id'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/clinics/new': {
      id: '/_authenticated/admin/clinics/new'
      path: '/admin/clinics/new'
      fullPath: '/admin/clinics/new'
      preLoaderRoute: typeof AuthenticatedAdminClinicsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/clinics/$id': {
      id: '/_authenticated/admin/clinics/$id'
      path: '/admin/clinics/$id'
      fullPath: '/admin/clinics/$id'
      preLoaderRoute: typeof AuthenticatedAdminClinicsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminClinicsIdRoute: typeof AuthenticatedAdminClinicsIdRoute
  AuthenticatedAdminClinicsNewRoute: typeof AuthenticatedAdminClinicsNewRoute
  AuthenticatedAdminOrganizationsIdRoute: typeof AuthenticatedAdminOrganizationsIdRoute
  AuthenticatedAdminOrganizationsNewRoute: typeof AuthenticatedAdminOrganizationsNewRoute
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
  AuthenticatedAdminUsersNewRoute: typeof AuthenticatedAdminUsersNewRoute
  AuthenticatedAdminAdminsIndexRoute: typeof AuthenticatedAdminAdminsIndexRoute
  AuthenticatedAdminClinicsIndexRoute: typeof AuthenticatedAdminClinicsIndexRoute
  AuthenticatedAdminOrganizationsIndexRoute: typeof AuthenticatedAdminOrganizationsIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminClinicsIdRoute: AuthenticatedAdminClinicsIdRoute,
  AuthenticatedAdminClinicsNewRoute: AuthenticatedAdminClinicsNewRoute,
  AuthenticatedAdminOrganizationsIdRoute:
    AuthenticatedAdminOrganizationsIdRoute,
  AuthenticatedAdminOrganizationsNewRoute:
    AuthenticatedAdminOrganizationsNewRoute,
  AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
  AuthenticatedAdminUsersNewRoute: AuthenticatedAdminUsersNewRoute,
  AuthenticatedAdminAdminsIndexRoute: AuthenticatedAdminAdminsIndexRoute,
  AuthenticatedAdminClinicsIndexRoute: AuthenticatedAdminClinicsIndexRoute,
  AuthenticatedAdminOrganizationsIndexRoute:
    AuthenticatedAdminOrganizationsIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
  PublicVerifyEmailRoute: typeof PublicVerifyEmailRoute
  PublicOnboardingCompleteRoute: typeof PublicOnboardingCompleteRoute
  PublicOnboardingReviewRoute: typeof PublicOnboardingReviewRoute
  PublicOnboardingStep1Route: typeof PublicOnboardingStep1Route
  PublicOnboardingStep2Route: typeof PublicOnboardingStep2Route
  PublicOnboardingStep3Route: typeof PublicOnboardingStep3Route
  PublicOnboardingStep4Route: typeof PublicOnboardingStep4Route
  PublicOnboardingStep5Route: typeof PublicOnboardingStep5Route
  PublicOnboardingIndexRoute: typeof PublicOnboardingIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
  PublicVerifyEmailRoute: PublicVerifyEmailRoute,
  PublicOnboardingCompleteRoute: PublicOnboardingCompleteRoute,
  PublicOnboardingReviewRoute: PublicOnboardingReviewRoute,
  PublicOnboardingStep1Route: PublicOnboardingStep1Route,
  PublicOnboardingStep2Route: PublicOnboardingStep2Route,
  PublicOnboardingStep3Route: PublicOnboardingStep3Route,
  PublicOnboardingStep4Route: PublicOnboardingStep4Route,
  PublicOnboardingStep5Route: PublicOnboardingStep5Route,
  PublicOnboardingIndexRoute: PublicOnboardingIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
