/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicVerifyEmailRouteImport } from './routes/_public/verify-email'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as PublicAcceptInviteRouteImport } from './routes/_public/accept-invite'
import { Route as AuthenticatedClinicRouteImport } from './routes/_authenticated/clinic'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as PublicOnboardingIndexRouteImport } from './routes/_public/onboarding/index'
import { Route as AuthenticatedClinicIndexRouteImport } from './routes/_authenticated/clinic/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as PublicOnboardingStep5RouteImport } from './routes/_public/onboarding/step-5'
import { Route as PublicOnboardingStep4RouteImport } from './routes/_public/onboarding/step-4'
import { Route as PublicOnboardingStep3RouteImport } from './routes/_public/onboarding/step-3'
import { Route as PublicOnboardingStep2RouteImport } from './routes/_public/onboarding/step-2'
import { Route as PublicOnboardingStep1RouteImport } from './routes/_public/onboarding/step-1'
import { Route as PublicOnboardingReviewRouteImport } from './routes/_public/onboarding/review'
import { Route as PublicOnboardingCompleteRouteImport } from './routes/_public/onboarding/complete'
import { Route as AuthenticatedClinicSettingsRouteImport } from './routes/_authenticated/clinic/settings'
import { Route as AuthenticatedClinicMembersRouteImport } from './routes/_authenticated/clinic/members'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminOrganizationsIndexRouteImport } from './routes/_authenticated/admin/organizations/index'
import { Route as AuthenticatedAdminClinicsIndexRouteImport } from './routes/_authenticated/admin/clinics/index'
import { Route as AuthenticatedAdminAdminsIndexRouteImport } from './routes/_authenticated/admin/admins/index'
import { Route as AuthenticatedAdminUsersNewRouteImport } from './routes/_authenticated/admin/users/new'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin/users/$id'
import { Route as AuthenticatedAdminOrganizationsNewRouteImport } from './routes/_authenticated/admin/organizations/new'
import { Route as AuthenticatedAdminOrganizationsIdRouteImport } from './routes/_authenticated/admin/organizations/$id'
import { Route as AuthenticatedAdminClinicsNewRouteImport } from './routes/_authenticated/admin/clinics/new'
import { Route as AuthenticatedAdminClinicsIdRouteImport } from './routes/_authenticated/admin/clinics/$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicVerifyEmailRoute = PublicVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAcceptInviteRoute = PublicAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedClinicRoute = AuthenticatedClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicOnboardingIndexRoute = PublicOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedClinicIndexRoute =
  AuthenticatedClinicIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClinicRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const PublicOnboardingStep5Route = PublicOnboardingStep5RouteImport.update({
  id: '/onboarding/step-5',
  path: '/onboarding/step-5',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOnboardingStep4Route = PublicOnboardingStep4RouteImport.update({
  id: '/onboarding/step-4',
  path: '/onboarding/step-4',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOnboardingStep3Route = PublicOnboardingStep3RouteImport.update({
  id: '/onboarding/step-3',
  path: '/onboarding/step-3',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOnboardingStep2Route = PublicOnboardingStep2RouteImport.update({
  id: '/onboarding/step-2',
  path: '/onboarding/step-2',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOnboardingStep1Route = PublicOnboardingStep1RouteImport.update({
  id: '/onboarding/step-1',
  path: '/onboarding/step-1',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOnboardingReviewRoute = PublicOnboardingReviewRouteImport.update({
  id: '/onboarding/review',
  path: '/onboarding/review',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOnboardingCompleteRoute =
  PublicOnboardingCompleteRouteImport.update({
    id: '/onboarding/complete',
    path: '/onboarding/complete',
    getParentRoute: () => PublicRoute,
  } as any)
const AuthenticatedClinicSettingsRoute =
  AuthenticatedClinicSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedClinicRoute,
  } as any)
const AuthenticatedClinicMembersRoute =
  AuthenticatedClinicMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedClinicRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrganizationsIndexRoute =
  AuthenticatedAdminOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClinicsIndexRoute =
  AuthenticatedAdminClinicsIndexRouteImport.update({
    id: '/clinics/',
    path: '/clinics/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminsIndexRoute =
  AuthenticatedAdminAdminsIndexRouteImport.update({
    id: '/admins/',
    path: '/admins/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersNewRoute =
  AuthenticatedAdminUsersNewRouteImport.update({
    id: '/users/new',
    path: '/users/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/users/$id',
    path: '/users/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrganizationsNewRoute =
  AuthenticatedAdminOrganizationsNewRouteImport.update({
    id: '/organizations/new',
    path: '/organizations/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrganizationsIdRoute =
  AuthenticatedAdminOrganizationsIdRouteImport.update({
    id: '/organizations/$id',
    path: '/organizations/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClinicsNewRoute =
  AuthenticatedAdminClinicsNewRouteImport.update({
    id: '/clinics/new',
    path: '/clinics/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClinicsIdRoute =
  AuthenticatedAdminClinicsIdRouteImport.update({
    id: '/clinics/$id',
    path: '/clinics/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/clinic': typeof AuthenticatedClinicRouteWithChildren
  '/accept-invite': typeof PublicAcceptInviteRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/clinic/members': typeof AuthenticatedClinicMembersRoute
  '/clinic/settings': typeof AuthenticatedClinicSettingsRoute
  '/onboarding/complete': typeof PublicOnboardingCompleteRoute
  '/onboarding/review': typeof PublicOnboardingReviewRoute
  '/onboarding/step-1': typeof PublicOnboardingStep1Route
  '/onboarding/step-2': typeof PublicOnboardingStep2Route
  '/onboarding/step-3': typeof PublicOnboardingStep3Route
  '/onboarding/step-4': typeof PublicOnboardingStep4Route
  '/onboarding/step-5': typeof PublicOnboardingStep5Route
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/clinic/': typeof AuthenticatedClinicIndexRoute
  '/onboarding/': typeof PublicOnboardingIndexRoute
  '/admin/clinics/$id': typeof AuthenticatedAdminClinicsIdRoute
  '/admin/clinics/new': typeof AuthenticatedAdminClinicsNewRoute
  '/admin/organizations/$id': typeof AuthenticatedAdminOrganizationsIdRoute
  '/admin/organizations/new': typeof AuthenticatedAdminOrganizationsNewRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/admin/users/new': typeof AuthenticatedAdminUsersNewRoute
  '/admin/admins/': typeof AuthenticatedAdminAdminsIndexRoute
  '/admin/clinics/': typeof AuthenticatedAdminClinicsIndexRoute
  '/admin/organizations/': typeof AuthenticatedAdminOrganizationsIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof PublicAcceptInviteRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/clinic/members': typeof AuthenticatedClinicMembersRoute
  '/clinic/settings': typeof AuthenticatedClinicSettingsRoute
  '/onboarding/complete': typeof PublicOnboardingCompleteRoute
  '/onboarding/review': typeof PublicOnboardingReviewRoute
  '/onboarding/step-1': typeof PublicOnboardingStep1Route
  '/onboarding/step-2': typeof PublicOnboardingStep2Route
  '/onboarding/step-3': typeof PublicOnboardingStep3Route
  '/onboarding/step-4': typeof PublicOnboardingStep4Route
  '/onboarding/step-5': typeof PublicOnboardingStep5Route
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/clinic': typeof AuthenticatedClinicIndexRoute
  '/onboarding': typeof PublicOnboardingIndexRoute
  '/admin/clinics/$id': typeof AuthenticatedAdminClinicsIdRoute
  '/admin/clinics/new': typeof AuthenticatedAdminClinicsNewRoute
  '/admin/organizations/$id': typeof AuthenticatedAdminOrganizationsIdRoute
  '/admin/organizations/new': typeof AuthenticatedAdminOrganizationsNewRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/admin/users/new': typeof AuthenticatedAdminUsersNewRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsIndexRoute
  '/admin/clinics': typeof AuthenticatedAdminClinicsIndexRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/clinic': typeof AuthenticatedClinicRouteWithChildren
  '/_public/accept-invite': typeof PublicAcceptInviteRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_public/verify-email': typeof PublicVerifyEmailRoute
  '/_authenticated/clinic/members': typeof AuthenticatedClinicMembersRoute
  '/_authenticated/clinic/settings': typeof AuthenticatedClinicSettingsRoute
  '/_public/onboarding/complete': typeof PublicOnboardingCompleteRoute
  '/_public/onboarding/review': typeof PublicOnboardingReviewRoute
  '/_public/onboarding/step-1': typeof PublicOnboardingStep1Route
  '/_public/onboarding/step-2': typeof PublicOnboardingStep2Route
  '/_public/onboarding/step-3': typeof PublicOnboardingStep3Route
  '/_public/onboarding/step-4': typeof PublicOnboardingStep4Route
  '/_public/onboarding/step-5': typeof PublicOnboardingStep5Route
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/clinic/': typeof AuthenticatedClinicIndexRoute
  '/_public/onboarding/': typeof PublicOnboardingIndexRoute
  '/_authenticated/admin/clinics/$id': typeof AuthenticatedAdminClinicsIdRoute
  '/_authenticated/admin/clinics/new': typeof AuthenticatedAdminClinicsNewRoute
  '/_authenticated/admin/organizations/$id': typeof AuthenticatedAdminOrganizationsIdRoute
  '/_authenticated/admin/organizations/new': typeof AuthenticatedAdminOrganizationsNewRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/_authenticated/admin/users/new': typeof AuthenticatedAdminUsersNewRoute
  '/_authenticated/admin/admins/': typeof AuthenticatedAdminAdminsIndexRoute
  '/_authenticated/admin/clinics/': typeof AuthenticatedAdminClinicsIndexRoute
  '/_authenticated/admin/organizations/': typeof AuthenticatedAdminOrganizationsIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/clinic'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/clinic/members'
    | '/clinic/settings'
    | '/onboarding/complete'
    | '/onboarding/review'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/onboarding/step-4'
    | '/onboarding/step-5'
    | '/admin/'
    | '/clinic/'
    | '/onboarding/'
    | '/admin/clinics/$id'
    | '/admin/clinics/new'
    | '/admin/organizations/$id'
    | '/admin/organizations/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/admin/admins/'
    | '/admin/clinics/'
    | '/admin/organizations/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/clinic/members'
    | '/clinic/settings'
    | '/onboarding/complete'
    | '/onboarding/review'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/onboarding/step-4'
    | '/onboarding/step-5'
    | '/admin'
    | '/clinic'
    | '/onboarding'
    | '/admin/clinics/$id'
    | '/admin/clinics/new'
    | '/admin/organizations/$id'
    | '/admin/organizations/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/admin/admins'
    | '/admin/clinics'
    | '/admin/organizations'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/admin'
    | '/_authenticated/clinic'
    | '/_public/accept-invite'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/reset-password'
    | '/_public/verify-email'
    | '/_authenticated/clinic/members'
    | '/_authenticated/clinic/settings'
    | '/_public/onboarding/complete'
    | '/_public/onboarding/review'
    | '/_public/onboarding/step-1'
    | '/_public/onboarding/step-2'
    | '/_public/onboarding/step-3'
    | '/_public/onboarding/step-4'
    | '/_public/onboarding/step-5'
    | '/_authenticated/admin/'
    | '/_authenticated/clinic/'
    | '/_public/onboarding/'
    | '/_authenticated/admin/clinics/$id'
    | '/_authenticated/admin/clinics/new'
    | '/_authenticated/admin/organizations/$id'
    | '/_authenticated/admin/organizations/new'
    | '/_authenticated/admin/users/$id'
    | '/_authenticated/admin/users/new'
    | '/_authenticated/admin/admins/'
    | '/_authenticated/admin/clinics/'
    | '/_authenticated/admin/organizations/'
    | '/_authenticated/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/verify-email': {
      id: '/_public/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof PublicVerifyEmailRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/accept-invite': {
      id: '/_public/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof PublicAcceptInviteRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/clinic': {
      id: '/_authenticated/clinic'
      path: '/clinic'
      fullPath: '/clinic'
      preLoaderRoute: typeof AuthenticatedClinicRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/onboarding/': {
      id: '/_public/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof PublicOnboardingIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/clinic/': {
      id: '/_authenticated/clinic/'
      path: '/'
      fullPath: '/clinic/'
      preLoaderRoute: typeof AuthenticatedClinicIndexRouteImport
      parentRoute: typeof AuthenticatedClinicRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_public/onboarding/step-5': {
      id: '/_public/onboarding/step-5'
      path: '/onboarding/step-5'
      fullPath: '/onboarding/step-5'
      preLoaderRoute: typeof PublicOnboardingStep5RouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/onboarding/step-4': {
      id: '/_public/onboarding/step-4'
      path: '/onboarding/step-4'
      fullPath: '/onboarding/step-4'
      preLoaderRoute: typeof PublicOnboardingStep4RouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/onboarding/step-3': {
      id: '/_public/onboarding/step-3'
      path: '/onboarding/step-3'
      fullPath: '/onboarding/step-3'
      preLoaderRoute: typeof PublicOnboardingStep3RouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/onboarding/step-2': {
      id: '/_public/onboarding/step-2'
      path: '/onboarding/step-2'
      fullPath: '/onboarding/step-2'
      preLoaderRoute: typeof PublicOnboardingStep2RouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/onboarding/step-1': {
      id: '/_public/onboarding/step-1'
      path: '/onboarding/step-1'
      fullPath: '/onboarding/step-1'
      preLoaderRoute: typeof PublicOnboardingStep1RouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/onboarding/review': {
      id: '/_public/onboarding/review'
      path: '/onboarding/review'
      fullPath: '/onboarding/review'
      preLoaderRoute: typeof PublicOnboardingReviewRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/onboarding/complete': {
      id: '/_public/onboarding/complete'
      path: '/onboarding/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof PublicOnboardingCompleteRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/clinic/settings': {
      id: '/_authenticated/clinic/settings'
      path: '/settings'
      fullPath: '/clinic/settings'
      preLoaderRoute: typeof AuthenticatedClinicSettingsRouteImport
      parentRoute: typeof AuthenticatedClinicRoute
    }
    '/_authenticated/clinic/members': {
      id: '/_authenticated/clinic/members'
      path: '/members'
      fullPath: '/clinic/members'
      preLoaderRoute: typeof AuthenticatedClinicMembersRouteImport
      parentRoute: typeof AuthenticatedClinicRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/organizations/': {
      id: '/_authenticated/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clinics/': {
      id: '/_authenticated/admin/clinics/'
      path: '/clinics'
      fullPath: '/admin/clinics/'
      preLoaderRoute: typeof AuthenticatedAdminClinicsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/admins/': {
      id: '/_authenticated/admin/admins/'
      path: '/admins'
      fullPath: '/admin/admins/'
      preLoaderRoute: typeof AuthenticatedAdminAdminsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users/new': {
      id: '/_authenticated/admin/users/new'
      path: '/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AuthenticatedAdminUsersNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/organizations/new': {
      id: '/_authenticated/admin/organizations/new'
      path: '/organizations/new'
      fullPath: '/admin/organizations/new'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/organizations/$id': {
      id: '/_authenticated/admin/organizations/$id'
      path: '/organizations/$id'
      fullPath: '/admin/organizations/$id'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clinics/new': {
      id: '/_authenticated/admin/clinics/new'
      path: '/clinics/new'
      fullPath: '/admin/clinics/new'
      preLoaderRoute: typeof AuthenticatedAdminClinicsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clinics/$id': {
      id: '/_authenticated/admin/clinics/$id'
      path: '/clinics/$id'
      fullPath: '/admin/clinics/$id'
      preLoaderRoute: typeof AuthenticatedAdminClinicsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminClinicsIdRoute: typeof AuthenticatedAdminClinicsIdRoute
  AuthenticatedAdminClinicsNewRoute: typeof AuthenticatedAdminClinicsNewRoute
  AuthenticatedAdminOrganizationsIdRoute: typeof AuthenticatedAdminOrganizationsIdRoute
  AuthenticatedAdminOrganizationsNewRoute: typeof AuthenticatedAdminOrganizationsNewRoute
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
  AuthenticatedAdminUsersNewRoute: typeof AuthenticatedAdminUsersNewRoute
  AuthenticatedAdminAdminsIndexRoute: typeof AuthenticatedAdminAdminsIndexRoute
  AuthenticatedAdminClinicsIndexRoute: typeof AuthenticatedAdminClinicsIndexRoute
  AuthenticatedAdminOrganizationsIndexRoute: typeof AuthenticatedAdminOrganizationsIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminClinicsIdRoute: AuthenticatedAdminClinicsIdRoute,
  AuthenticatedAdminClinicsNewRoute: AuthenticatedAdminClinicsNewRoute,
  AuthenticatedAdminOrganizationsIdRoute:
    AuthenticatedAdminOrganizationsIdRoute,
  AuthenticatedAdminOrganizationsNewRoute:
    AuthenticatedAdminOrganizationsNewRoute,
  AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
  AuthenticatedAdminUsersNewRoute: AuthenticatedAdminUsersNewRoute,
  AuthenticatedAdminAdminsIndexRoute: AuthenticatedAdminAdminsIndexRoute,
  AuthenticatedAdminClinicsIndexRoute: AuthenticatedAdminClinicsIndexRoute,
  AuthenticatedAdminOrganizationsIndexRoute:
    AuthenticatedAdminOrganizationsIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedClinicRouteChildren {
  AuthenticatedClinicMembersRoute: typeof AuthenticatedClinicMembersRoute
  AuthenticatedClinicSettingsRoute: typeof AuthenticatedClinicSettingsRoute
  AuthenticatedClinicIndexRoute: typeof AuthenticatedClinicIndexRoute
}

const AuthenticatedClinicRouteChildren: AuthenticatedClinicRouteChildren = {
  AuthenticatedClinicMembersRoute: AuthenticatedClinicMembersRoute,
  AuthenticatedClinicSettingsRoute: AuthenticatedClinicSettingsRoute,
  AuthenticatedClinicIndexRoute: AuthenticatedClinicIndexRoute,
}

const AuthenticatedClinicRouteWithChildren =
  AuthenticatedClinicRoute._addFileChildren(AuthenticatedClinicRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedClinicRoute: typeof AuthenticatedClinicRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedClinicRoute: AuthenticatedClinicRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicAcceptInviteRoute: typeof PublicAcceptInviteRoute
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
  PublicVerifyEmailRoute: typeof PublicVerifyEmailRoute
  PublicOnboardingCompleteRoute: typeof PublicOnboardingCompleteRoute
  PublicOnboardingReviewRoute: typeof PublicOnboardingReviewRoute
  PublicOnboardingStep1Route: typeof PublicOnboardingStep1Route
  PublicOnboardingStep2Route: typeof PublicOnboardingStep2Route
  PublicOnboardingStep3Route: typeof PublicOnboardingStep3Route
  PublicOnboardingStep4Route: typeof PublicOnboardingStep4Route
  PublicOnboardingStep5Route: typeof PublicOnboardingStep5Route
  PublicOnboardingIndexRoute: typeof PublicOnboardingIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAcceptInviteRoute: PublicAcceptInviteRoute,
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
  PublicVerifyEmailRoute: PublicVerifyEmailRoute,
  PublicOnboardingCompleteRoute: PublicOnboardingCompleteRoute,
  PublicOnboardingReviewRoute: PublicOnboardingReviewRoute,
  PublicOnboardingStep1Route: PublicOnboardingStep1Route,
  PublicOnboardingStep2Route: PublicOnboardingStep2Route,
  PublicOnboardingStep3Route: PublicOnboardingStep3Route,
  PublicOnboardingStep4Route: PublicOnboardingStep4Route,
  PublicOnboardingStep5Route: PublicOnboardingStep5Route,
  PublicOnboardingIndexRoute: PublicOnboardingIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
