export const SEED_CONFIG = {
  PASSWORD_HASH_ROUNDS: 10,
  TEST_PASSWORD: 'Test123!',
  ADMIN_PASSWORD: 'Admin123!',
  FAKER_SEED: 12345,

  // Volume
  PATIENT_COUNT: 100,
  CONVERSATION_COUNT: 80,
  MESSAGE_COUNT: 400,
  APPOINTMENT_COUNT: 200,
  AUDIT_LOG_COUNT: 50,

  // Date ranges
  APPOINTMENTS_PAST_DAYS: 90,
  APPOINTMENTS_FUTURE_DAYS: 14,
  AUDIT_LOGS_PAST_DAYS: 7,
}
